// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CloudCounter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("created")]
        public DateTimeOffset? Created { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("lastAction")]
        public string LastAction { get; set; }

        [JsonProperty("lastRead")]
        public DateTimeOffset? LastRead { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset? LastUpdated { get; set; }

        [JsonProperty("numberOfDigits")]
        public long? NumberOfDigits { get; set; }

        [JsonProperty("ordinal")]
        public string Ordinal { get; set; }

        [JsonProperty("value")]
        public long? Value { get; set; }

        [JsonProperty("words")]
        public string Words { get; set; }

        [JsonProperty("isEven")]
        public bool? IsEven { get; set; }

        [JsonProperty("isNegative")]
        public bool? IsNegative { get; set; }

        [JsonProperty("isZero")]
        public bool? IsZero { get; set; }

        [JsonProperty("isPrime")]
        public bool? IsPrime { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
